<#
.SYNOPSIS
    Intune Proactive Remediation - DETECTION script (used standalone).

.DESCRIPTION
    Collects device information and POSTs it to the Log Ingestion Function App.
    The Function forwards the payload to the Data Collection Rule, which writes
    it to the custom Log Analytics table.

    This script was generated by the Log Ingestion Portal. The properties built
    in Get-DeviceData match the columns in the generated schema/columns.json. To
    change what is collected, re-run the portal, regenerate both files, and
    redeploy the infrastructure with deploy.ps1.

.NOTES
    Run in the DETECTION slot of a Proactive Remediation on a schedule. It exits
    0 after a successful upload (device stays 'compliant') and exits 1 only on a
    real failure, which is surfaced in the Intune Output column and the IME log.

    Treat the whole $FunctionUrl as a secret (it includes ?code=<key>) and rotate
    the key periodically (Function App -> App keys).

.PARAMETER PreviewData
    Print the collected data as JSON and exit WITHOUT uploading. Run locally as
    SYSTEM (e.g. psexec -s -i powershell.exe) to see the exact body that would be
    sent. Paste that JSON into the portal's "Build columns.json from sample data"
    tool to generate a matching schema after you add your own properties.
#>

param(
    [switch]$PreviewData
)

# ----------------------------------------------------------------------------
# Configuration - generated by the Log Ingestion Portal.
# ----------------------------------------------------------------------------
$FunctionUrl = '__FUNCTION_URL__'

# Device authentication (JWT). The script signs a short-lived JWT with the
# device's Entra-join (MS-Organization-Access) certificate and sends it as
# Authorization: Bearer. The Function requires this on every request.
$UseDeviceJwt = __USE_JWT__

# Version stamped into the IntuneScriptVersion column so you can tell whether
# data came from an older script or the current one. Bump it when you change
# the script.
$ScriptVersion = '__SCRIPT_VERSION__'
# ----------------------------------------------------------------------------

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# ----------------------------------------------------------------------------
# Diagnostics. Intune surfaces only the LAST line of stdout (Output column) plus
# the exit code, so the script writes a single summary line at the end. Full
# timestamped detail goes into the Intune Management Extension (IME) Logs folder.
# ----------------------------------------------------------------------------
$script:LogDir   = Join-Path $env:ProgramData 'Microsoft\IntuneManagementExtension\Logs'
$script:LogFile  = Join-Path $script:LogDir 'LogIngestion-Remediate.log'
$script:Warnings = New-Object System.Collections.Generic.List[string]

function Write-Log {
    param([ValidateSet('INFO', 'WARN', 'ERROR')][string]$Level = 'INFO', [string]$Message)
    $line = "$((Get-Date).ToUniversalTime().ToString('o')) [$Level] $Message"
    try {
        if (-not (Test-Path $script:LogDir)) { New-Item -Path $script:LogDir -ItemType Directory -Force | Out-Null }
        Add-Content -Path $script:LogFile -Value $line
    }
    catch { }
    if ($Level -eq 'WARN') { $script:Warnings.Add($Message) }
}

function Get-EntraJoinCertificate {
    $joinKeyPath = 'HKLM:\SYSTEM\CurrentControlSet\Control\CloudDomainJoin\JoinInfo'
    if (-not (Test-Path $joinKeyPath)) { throw 'Device is not Entra-joined (CloudDomainJoin/JoinInfo missing).' }
    $thumbOrId = Get-ChildItem -Path $joinKeyPath | Select-Object -First 1 -ExpandProperty PSChildName
    if (-not $thumbOrId) { throw 'No JoinInfo subkey present.' }

    $cert = Get-ChildItem -Path Cert:\LocalMachine\My -Recurse | Where-Object {
        $_.Issuer -like '*MS-Organization-Access*' -and
        ( $_.Thumbprint -eq $thumbOrId -or $_.Subject -like "CN=$thumbOrId" )
    } | Select-Object -First 1
    if (-not $cert) { throw "MS-Organization-Access certificate not found for join key '$thumbOrId'." }
    if (-not $cert.HasPrivateKey) { throw 'MS-Organization-Access certificate has no accessible private key.' }
    return $cert
}

function Get-EntraTenantId {
    $p = 'HKLM:\SYSTEM\CurrentControlSet\Control\CloudDomainJoin\TenantInfo'
    if (-not (Test-Path $p)) { throw 'TenantInfo registry key missing.' }
    return (Get-ChildItem -Path $p | Select-Object -First 1 -ExpandProperty PSChildName)
}

function New-DeviceJwt {
    param(
        [System.Security.Cryptography.X509Certificates.X509Certificate2]$Cert,
        [string]$TenantId,
        [string]$DeviceId,
        [string]$Audience
    )
    $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $x5t = [Convert]::ToBase64String($Cert.GetCertHash()).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    $x5c = @([Convert]::ToBase64String($Cert.RawData))
    $chain = [System.Security.Cryptography.X509Certificates.X509Chain]::new()
    try {
        $null = $chain.Build($Cert)
        $chainValues = @(
            $chain.ChainElements |
            ForEach-Object { [Convert]::ToBase64String($_.Certificate.RawData) } |
            Select-Object -Unique
        )
        if ($chainValues.Count -gt 0) {
            $x5c = $chainValues
        }
    }
    finally {
        $chain.Dispose()
    }
    $header = [ordered]@{ alg = 'RS256'; typ = 'JWT'; x5t = $x5t; x5c = $x5c }
    $payload = [ordered]@{
        tid   = $TenantId
        did   = $DeviceId
        nonce = [Guid]::NewGuid().ToString('N')
        iat   = $now
        exp   = $now + 300
    }
    if ($Audience) { $payload.aud = $Audience }

    $b64url = {
        param($o)
        $bytes = [Text.Encoding]::UTF8.GetBytes(($o | ConvertTo-Json -Compress -Depth 5))
        [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    }
    $h = & $b64url $header
    $p = & $b64url $payload
    $rsa = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($Cert)
    if (-not $rsa) { throw 'Failed to get RSA private key from device cert.' }
    $sig = $rsa.SignData(
        [Text.Encoding]::ASCII.GetBytes("$h.$p"),
        [System.Security.Cryptography.HashAlgorithmName]::SHA256,
        [System.Security.Cryptography.RSASignaturePadding]::Pkcs1)
    $s = [Convert]::ToBase64String($sig).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    "$h.$p.$s"
}

function Get-AuthHeader {
    if (-not $UseDeviceJwt) { return @{} }

    $isSystem = $false
    try {
        $isSystem = ([Security.Principal.WindowsIdentity]::GetCurrent()).IsSystem
    }
    catch { }

    try {
        $cert = Get-EntraJoinCertificate
        $deviceId = ($cert.Subject -replace '^CN=', '').Trim()
        $tenantId = Get-EntraTenantId
        $audience = $null
        try { $audience = 'https://' + ([uri]$FunctionUrl).Host } catch { }
        $jwt = New-DeviceJwt -Cert $cert -TenantId $tenantId -DeviceId $deviceId -Audience $audience
        return @{ Authorization = "Bearer $jwt" }
    }
    catch {
        $msg = $_.Exception.Message
        if (-not $isSystem -and ($msg -match 'Invalid provider type|Keyset does not exist|private key|NTE_')) {
            throw "Device JWT signing requires SYSTEM context. The Entra-join (MS-Organization-Access) certificate's private key is TPM-bound and only accessible to SYSTEM. Run this via Intune Proactive Remediation with 'Run this script using the logged-on credentials = No', or test locally with 'psexec -s -i powershell.exe'. (Current user: $([Security.Principal.WindowsIdentity]::GetCurrent().Name); underlying error: $msg)"
        }
        throw "Failed to build device JWT: $msg"
    }
}

function Invoke-Safe {
    # Run a collector scriptblock and never let a failure (missing cmdlet, no
    # admin rights, no feature installed) break the whole upload. Logs a named
    # WARN (surfaced to Intune via the end-of-run summary) and returns $Default.
    param(
        [Parameter(Mandatory, Position = 0)][string]$Name,
        [Parameter(Mandatory, Position = 1)][scriptblock]$Script,
        $Default = $null
    )
    try { & $Script }
    catch {
        Write-Log -Level WARN -Message "Collector '$Name' failed: $($_.Exception.Message)"
        return $Default
    }
}

function Get-DeviceData {
    # Generated by the Log Ingestion Portal. Returns a TABLE-KEYED object
    #   [ordered]@{ 'Table1_CL' = @( [pscustomobject]@{...} ); 'Table2_CL' = @( ... ) }
    # so each record is routed to the right custom table. Each record's properties
    # must match the columns in that table's generated columns.json; properties
    # without a matching column are silently dropped by the DCR.
__GET_DEVICE_DATA_BODY__
}

function Send-Telemetry {
    param([Parameter(Mandatory)]$Payload)

    # $Payload is the table-keyed object from Get-DeviceData. Post it as-is; the
    # Function fans each table's records out to its DCR stream.
    $body = ConvertTo-Json -InputObject $Payload -Depth 10
    $uri = $FunctionUrl
    $headers = Get-AuthHeader

    $maxAttempts = 3
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        try {
            Invoke-RestMethod -Method Post -Uri $uri -Body $body -ContentType 'application/json' -Headers $headers -TimeoutSec 60 | Out-Null
            return $true
        }
        catch {
            # Pull the HTTP status and the server's JSON error body. The Function
            # returns a reason such as { "error": "Unknown table 'X'" } — without
            # this the caller only sees a bare "(400) Bad Request".
            $status = $null
            try { $status = [int]$_.Exception.Response.StatusCode } catch { }
            $detail = if ($_.ErrorDetails -and $_.ErrorDetails.Message) { $_.ErrorDetails.Message } else { $null }
            if (-not $detail) {
                try {
                    $response = $_.Exception.Response
                    if ($response) {
                        $stream = $response.GetResponseStream()
                        if ($stream) {
                            $reader = New-Object System.IO.StreamReader($stream)
                            try {
                                $detail = $reader.ReadToEnd()
                            }
                            finally {
                                $reader.Dispose()
                            }
                        }
                    }
                }
                catch { }
            }

            if ($detail) {
                try {
                    $parsed = $detail | ConvertFrom-Json -ErrorAction Stop
                    $pieces = @()
                    if ($parsed.code) { $pieces += [string]$parsed.code }
                    if ($parsed.error) { $pieces += [string]$parsed.error }
                    if ($parsed.reason) { $pieces += [string]$parsed.reason }
                    if ($parsed.message) { $pieces += [string]$parsed.message }
                    if ($parsed.configuredTables) { $pieces += "configuredTables=$([string]$parsed.configuredTables)" }
                    if ($parsed.payloadType) { $pieces += "payloadType=$([string]$parsed.payloadType)" }
                    if ($pieces.Count -gt 0) {
                        $detail = ($pieces -join ' | ')
                    }
                }
                catch {
                    $detail = ($detail -replace '[\r\n]+', ' ').Trim()
                }
            }

            $info = (@(if ($status) { "HTTP $status" }, $detail) | Where-Object { $_ }) -join ' - '

            # 4xx is a client/payload problem (e.g. a table not yet deployed to
            # the Function's DCR_STREAMS) — retrying cannot help, so fail at once
            # with the server's reason instead of after three attempts.
            if ($status -ge 400 -and $status -lt 500) {
                throw "Upload rejected ($info)."
            }
            if ($attempt -eq $maxAttempts) {
                throw "Upload failed after $maxAttempts attempt(s)$(if ($info) { " ($info)" }): $($_.Exception.Message)"
            }
            Start-Sleep -Seconds ([math]::Pow(2, $attempt))
        }
    }
}

# Preview mode: print the collected JSON and exit (no upload). Run locally as
# SYSTEM (e.g. psexec -s -i powershell.exe) to see exactly what would be sent,
# then paste it into the portal's "Build columns.json from sample data" tool.
if ($PreviewData) {
    ConvertTo-Json -InputObject (Get-DeviceData) -Depth 10
    return
}

try {
    Write-Log -Level INFO -Message ('Intune script v' + $ScriptVersion + ' started.')
    $data = Get-DeviceData
    Send-Telemetry -Payload $data | Out-Null

    if ($script:Warnings.Count -gt 0) {
        $summary = "Telemetry uploaded with $($script:Warnings.Count) collector warning(s): " + ($script:Warnings -join '; ')
    }
    else {
        $summary = 'Telemetry uploaded successfully.'
    }
    Write-Log -Level INFO -Message $summary
    Write-Output "$summary Log: $script:LogFile"
    exit 0
}
catch {
    $err = "Remediation failed: $($_.Exception.Message)"
    Write-Log -Level ERROR -Message $err
    Write-Output "$err Log: $script:LogFile"
    exit 1
}
